name: "Linting"
on:
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  MarkdownLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: 16
    - run: npm install
    - run: npm run markdown-lint
  GeneralLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: 16
    - run: npm install
    - run: npm run general-lint
